### PR TITLE
Merge the changes on the 2 branches

### PR DESCRIPTION
**Pull request by aryanchari06**
Merging will result in : 
adding about us page on the main branch
adding services page on the main branch

### CODE REVIEW

**Comment by raushcoder07** [comment]
new contributer

**Review by aryanchari06 — COMMENTED** [review]
Submitting review

**Review by raushcoder07 — APPROVED** [review]

**Review by raushcoder07 — CHANGES_REQUESTED** [review]
update

**Review by raushcoder07 — APPROVED** [review]
apporved

**Comment by aryanchari06** [comment]
Please try approving pull request now, I have resolved conflicts that had occurred

**Review by aryanchari06 — COMMENTED** [review]
Review complete, occurirng conflicts are resolved

**Pull request closed without merging**
